# Configuración de Jekyll
title: Portfolio
description: This web page will contain my portfolio
author: Carlos Wyller Villanueva Machado
url: https://cwvillanuevam.github.io/Portfolio/

# Configuración de GitHub Pages
remote_theme: cwvillanuevam/Portfolio
