name: Publicar sitio web

on:
  push:
    branches:
      - main  # Reemplaza "main" con el nombre de tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install        
      - name: Build site
        run: bundle exec jekyll build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./public
